yearbook/config/routes.rb
Rails.application.routes.draw do
  resources :majors
  resources :students

  namespace :api do
    jsonapi_resources :majors
    jsonapi_resources :students
  end
end

yearbook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yearbook/app/models/major.rb
class Major < ApplicationRecord
  has_many :students

  def freaking_long_process
    sleep 1
    0
  end
end

yearbook/app/models/student.rb
class Student < ApplicationRecord
  # touch: true -> updates major.updated_at when student obj updated
  # it will only be activated when the student record changes
  belongs_to :major, touch: true
end

yearbook/app/controllers/api/majors_controller.rb
class Api::MajorsController < JSONAPI::ResourceController

end

yearbook/app/controllers/api/students_controller.rb
class Api::StudentsController < JSONAPI::ResourceController

end

yearbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

yearbook/app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:name)
    end
end

yearbook/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    fresh_when(etag: @students, last_modified: @students.first.updated_at)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @majors = Major.all
  end

  # GET /students/1/edit
  def edit
    @majors = Major.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :phone_number, :graduation_year, :major_id)
    end
end

yearbook/app/helpers/application_helper.rb
module ApplicationHelper
end

yearbook/app/helpers/majors_helper.rb
module MajorsHelper
end

yearbook/app/helpers/students_helper.rb
module StudentsHelper
end

yearbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yearbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

yearbook/app/views/majors/_form.html.erb
<%= form_for(major) do |f| %>
  <% if major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
      <% major.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

yearbook/app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

yearbook/app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>
<% cache @majors do %>
  <h1>Majors</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @majors.each do |major| %>
        <tr>
          <% major.freaking_long_process %>
          <td><%= major.name %></td>
          <td><%= link_to 'Show', major %></td>
          <td><%= link_to 'Edit', edit_major_path(major) %></td>
          <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Major', new_major_path %>
<% end %>

yearbook/app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Back', majors_path %>

yearbook/app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @major.name %>
</p>

<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>

yearbook/app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :graduation_year %>
    <%= f.number_field :graduation_year %>
  </div>

  <div class="field">
    <%= f.label :major %>
    <% cache @majors do %>
      <%= f.collection_select(:major_id, @majors, :id, :name) %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

yearbook/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

yearbook/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Phone number</th>
      <th>Graduation year</th>
      <th>Major</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.phone_number %></td>
        <td><%= student.graduation_year %></td>
        <td><%= student.major.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

yearbook/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

yearbook/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @student.phone_number %>
</p>

<p>
  <strong>Graduation year:</strong>
  <%= @student.graduation_year %>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>